name: Clear test caches
description: Remove pytest and Python caches
runs:
  using: composite
  steps:
    - name: Remove caches
      shell: bash
      run: |
        cache_dir="${PYTEST_CACHE_DIR:-${RUNNER_TEMP:-/tmp}/pytest_cache}"

        rm -rf "$cache_dir" .pytest_cache .cache
        find . -type d -name '__pycache__' -exec rm -rf {} +
        find . -name '*.pyc' -delete
