services:
  gptoss:
    ports:
      - "8003:8000"
    volumes:
      - gptoss_workspace:/workspace
    environment:
      - VLLM_DEVICE=cpu
      - VLLM_LOGGING_LEVEL=DEBUG
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health"]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 5s
    networks:
      - gptoss_net

  gptoss_check:
    environment:
      VLLM_TARGET_DEVICE: cpu

  data_handler:
    profiles: ["gpu-required"]

  model_builder:
    profiles: ["gpu-required"]

  trade_manager:
    profiles: ["gpu-required"]

  bot:
    profiles: ["gpu-required"]

networks:
  gptoss_net:
    name: gptoss_net
    driver: bridge

volumes:
  gptoss_workspace:
