services:
  gptoss:
    build:
      context: .
      dockerfile: Dockerfile.gptoss
    command: []
    ports:
      - "8003:8000"
    volumes:
      - gptoss_workspace:/workspace
    environment:
      VLLM_LOGGING_LEVEL: DEBUG
      MODEL: ${MODEL:-openai/gpt-oss-20b}
      VLLM_DEVICE: cpu
      VLLM_FORCE_CPU: "1"
      VLLM_DEFAULT_PLATFORM: cpu
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health"]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 5s
    networks:
      - gptoss_net

networks:
  gptoss_net:
    name: gptoss_net
    driver: bridge

volumes:
  gptoss_workspace:
