services:
  gptoss:
    image: substratusai/vllm:main-cpu
    command: >
      --model TinyLlama/TinyLlama-1.1B-Chat-v1.0 \
      --host 0.0.0.0 --port 8000 \
      --device cpu
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 120s
