services:
  gptoss:
    image: vllm/vllm-openai:latest
    ports:
      - "8003:8000"
    volumes:
      - gptoss_workspace:/workspace
    command: >
      --host 0.0.0.0 --port 8000
      --model ${MODEL_ID:-Qwen/Qwen2.5-0.5B-Instruct}
      --device cpu
    environment:
      VLLM_TARGET_DEVICE: cpu
      VLLM_LOGGING_LEVEL: DEBUG
      CUDA_VISIBLE_DEVICES: ""
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health"]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 5s
    networks:
      - gptoss_net

  gptoss_check:
    environment:
      VLLM_TARGET_DEVICE: cpu

networks:
  gptoss_net:
    name: gptoss_net
    driver: bridge

volumes:
  gptoss_workspace:
