services:
  gptoss:
    command:
      - python
      - -m
      - vllm.entrypoints.openai.api_server
      - --device
      - cpu
      - --model
      - ${MODEL}
      - --host
      - 0.0.0.0
    environment:
      CUDA_VISIBLE_DEVICES: ""
      VLLM_LOGGING_LEVEL: "DEBUG"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 120s
