services:
  gptoss:
    image: busybox
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 1s
  gptoss_check:
    image: busybox
    command: ["sh", "-c", "echo 'skipping gptoss check'"]
