---
name: Dependency Graph Auto Submission

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  auto-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Component detection
        uses: advanced-security/component-detection-dependency-submission-action@v0.1.0  # yamllint disable-line rule:line-length
        with:
          detectorArgs: Pip=EnableIfDefaultOff

