name: Dependency Graph Auto Submission

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  auto-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Component detection
        uses: advanced-security/component-detection-dependency-submission-action@v0.1.0
        env:
          PipReportOverrideBehavior: SourceCodeScan
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
