name: Setup environment
description: Prepare Python environment with cached dependencies
inputs:
  python-version:
    description: Python version to use
    required: true
  device:
    description: Target device
runs:
  using: composite
  steps:
    - name: Initial cleanup
      shell: bash
      run: rm -rf build/
    - name: Cleanup git submodules
      shell: bash
      run: >-
        git submodule foreach --recursive sh -c "git config --quiet --local gc.auto 0 || :" || :
    - name: Prepare workspace directories
      shell: bash
      run: |
        mkdir -p "$RUNNER_TEMP/tmp" "$RUNNER_TEMP/pip-cache" "$RUNNER_TEMP/pycache" "$RUNNER_TEMP/pytest_cache" "$RUNNER_TEMP/venv"
    - name: Configure temp directories
      shell: bash
      run: |
        mkdir -p "$RUNNER_TEMP/tmp" "$RUNNER_TEMP/pip-cache"
        echo "TMPDIR=$RUNNER_TEMP/tmp" >> $GITHUB_ENV
        echo "PIP_CACHE_DIR=$RUNNER_TEMP/pip-cache" >> $GITHUB_ENV
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Get pip cache dir
      id: pip-cache
      shell: bash
      run: |
        dir=$(python -m pip cache dir)
        echo "dir=$dir" >> "$GITHUB_OUTPUT"
    - name: Cache pip wheels
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: >-
          ${{ runner.os }}-pip-${{ inputs.device }}-py${{ inputs.python-version }}-${{ hashFiles('requirements-ci.txt', 'requirements-cpu.txt') }}
    - name: Cache virtualenv
      id: cache-venv
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ${{ runner.temp }}/venv
        key: >-
          ${{ runner.os }}-venv-${{ inputs.device }}-py${{ inputs.python-version }}-${{ hashFiles('requirements-ci.txt', 'requirements-cpu.txt') }}
    - name: Set up virtual environment
      shell: bash
      run: |
        attempts=3
        VENV_PATH="$RUNNER_TEMP/venv"

        if [ ! -f "$VENV_PATH/bin/activate" ]; then
          python -m venv "$VENV_PATH"
        fi
        source "$VENV_PATH/bin/activate"
        mkdir -p "$RUNNER_TEMP/tmp" "$RUNNER_TEMP/pip-cache"
        export TMPDIR="$RUNNER_TEMP/tmp"
        export PIP_CACHE_DIR="$RUNNER_TEMP/pip-cache"
        export PIP_DEFAULT_TIMEOUT=60

        for attempt in $(seq 1 "$attempts"); do
          echo "[setup-env] Upgrading pip and build tools (attempt $attempt/$attempts)"
          if python -m pip install --upgrade 'pip>=24.0' 'setuptools>=80.9.0,<81' wheel; then
            break
          fi

          if [ "$attempt" -eq "$attempts" ]; then
            echo "[setup-env] Failed to upgrade pip after $attempts attempts"
            exit 1
          fi

          sleep 10
        done

        for attempt in $(seq 1 "$attempts"); do
          echo "[setup-env] Installing requirements (attempt $attempt/$attempts)"
          if python -m pip install -r requirements-ci.txt -r requirements-cpu.txt; then
            break
          fi

          if [ "$attempt" -eq "$attempts" ]; then
            echo "[setup-env] Failed to install requirements after $attempts attempts"
            exit 1
          fi

          sleep 10
        done

        echo "$VENV_PATH/bin" >> $GITHUB_PATH
        printf 'VIRTUAL_ENV=%s\n' "$VENV_PATH" >> "$GITHUB_ENV"
        printf 'PATH=%s:%s\n' "$VENV_PATH/bin" "$PATH" >> "$GITHUB_ENV"
