name: dependency-submission

on:
  push:
    branches:
      - main
    paths:
      - "requirements*.txt"
      - "requirements*.in"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  submit:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.x'
      - name: Prepare requirements
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          detectorArgs: Pip=EnableIfDefaultOff
