name: Dependency Submission

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Component detection
        uses: advanced-security/component-detection-dependency-submission-action@v0.1.0
        with:
          detectorArgs: Pip=EnableIfDefaultOff
          detectorsCategories: Pip
