name: dependency-submission

on:
  push:
    branches:
      - main
    paths:
      - "requirements*.txt"
      - "requirements*.in"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  submit:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare requirements
        run: |
          awk '/^ccxtpro/ {skip=1; next} skip && /^[ \t]/ {next} {skip=0; print}' \
            requirements.out > requirements-submission.txt
      - name: Submit dependency graph
        uses: github/dependency-submission-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          requirements: requirements-submission.txt
