name: dependency-submission

on:
  push:
    branches: [ main ]
    paths:
      - "requirements*.txt"
      - "requirements*.in"
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare requirements
        run: |
          sed '/^ccxtpro/d' requirements.out > requirements-submission.txt
      - name: Submit dependency graph
        uses: github/dependency-submission-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          requirements: requirements-submission.txt
