name: dependency-submission

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types:
      - 'dependency_graph/auto_submission'

permissions:
  contents: read
  # GitHub rejects the legacy dependency graph permission scope for this workflow; grant
  # `security-events` instead to satisfy the dependency submission API while keeping
  # permissions minimal.
  security-events: write

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.11'
      - name: Detect dependency manifest changes
        id: detect
        env:
          BEFORE: ${{ github.event.before || github.event.client_payload.before || github.event.client_payload.base_sha || '' }}
          AFTER: ${{ github.sha || github.event.client_payload.after || github.event.client_payload.head_sha || github.event.client_payload.sha || '' }}
        run: |
          python <<'PY'
          from __future__ import annotations

          import fnmatch
          import os
          import subprocess
          from pathlib import Path
          from typing import Sequence

          patterns: Sequence[str] = (
              "requirements*.txt",
              "requirements*.in",
              "requirements*.out",
          )
          before = os.environ.get("BEFORE") or ""
          after = os.environ.get("AFTER") or ""

          diff_failed = False
          changed: list[str]

          if not after:
              print(
                  "::warning::Missing GITHUB_SHA value; assuming dependency manifests changed.",
                  flush=True,
              )
              diff_failed = True
              changed = []
          else:
              if not before or set(before) == {"0"}:
                  before = f"{after}^"

              try:
                  completed = subprocess.run(
                      ["git", "diff", "--name-only", before, after],
                      check=True,
                      stdout=subprocess.PIPE,
                      text=True,
                  )
              except subprocess.CalledProcessError as exc:
                  print(f"::warning::Unable to determine diff: {exc}", flush=True)
                  diff_failed = True
                  changed = []
              except Exception as exc:  # pragma: no cover - defensive guard for CI
                  print(
                      "::warning::Unexpected error while detecting manifest changes:",
                      exc,
                      flush=True,
                  )
                  diff_failed = True
                  changed = []
              else:
                  files = [
                      line.strip()
                      for line in completed.stdout.splitlines()
                      if line.strip()
                  ]
                  changed = []
                  for file in files:
                      if not file:
                          continue
                      try:
                          filename = Path(file).name
                      except Exception:
                          filename = file
                      if any(
                          fnmatch.fnmatch(file, pattern)
                          or fnmatch.fnmatch(filename, pattern)
                          for pattern in patterns
                      ):
                          changed.append(file)

          changed_flag = "true" if diff_failed or bool(changed) else "false"
          output_path = os.environ.get("GITHUB_OUTPUT")
          if not output_path:
              print(
                  "::warning::GITHUB_OUTPUT is not available; downstream steps will be skipped.",
                  flush=True,
              )
          else:
              try:
                  with open(output_path, "a", encoding="utf-8") as stream:
                      stream.write(f"changed={changed_flag}\n")
                      if changed:
                          stream.write("files<<EOF\n")
                          stream.write("\n".join(changed))
                          stream.write("\nEOF\n")
              except OSError as exc:  # pragma: no cover - filesystem guard for CI
                  print(
                      "::warning::Unable to write change detection outputs:",
                      exc,
                      flush=True,
                  )

          if changed_flag == "true" and not changed and diff_failed:
              print(
                  "Diff calculation failed; proceeding with dependency snapshot submission.",
                  flush=True,
              )
          elif changed:
              print("Dependency manifest changes detected:", flush=True)
              for path in changed:
                  print(f"  - {path}", flush=True)
          else:
              print("No dependency manifest changes detected.", flush=True)
          PY
      - name: Prepare requirements
        if: >-
          steps.detect.outputs.changed == 'true' ||
          github.event_name == 'workflow_dispatch' ||
          github.event_name == 'repository_dispatch'
        run: |
          python <<'PY'
          from pathlib import Path

          patterns = ("requirements*.txt", "requirements*.in", "requirements*.out")
          excluded = {
              ".git",
              ".hg",
              ".nox",
              ".tox",
              ".venv",
              "__pycache__",
              "env",
              "node_modules",
              "site-packages",
              "venv",
          }

          def is_excluded(target: Path) -> bool:
              return any(part in excluded for part in target.parts)

          for pattern in patterns:
              for path in Path(".").rglob(pattern):
                  if is_excluded(path.parent):
                      continue
                  try:
                      original = path.read_text(encoding="utf-8")
                  except UnicodeDecodeError as exc:
                      print(
                          f"Skipping {path} due to encoding error: {exc}",
                          flush=True,
                      )
                      continue
                  lines = original.splitlines(keepends=True)
                  filtered: list[str] = []
                  for line in lines:
                      stripped = line.lstrip()
                      stripped_lower = stripped.lower()
                      if stripped_lower.startswith("ccxtpro"):
                          continue
                      if stripped_lower.startswith("#") and "ccxtpro" in stripped_lower:
                          continue
                      filtered.append(line)
                  if filtered != lines:
                      updated = "".join(filtered)
                      path.write_text(updated, encoding="utf-8")
          PY
      - name: Install dependency snapshot dependencies
        if: >-
          steps.detect.outputs.changed == 'true' ||
          github.event_name == 'workflow_dispatch' ||
          github.event_name == 'repository_dispatch'
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
      - name: Submit dependency snapshot
        if: >-
          steps.detect.outputs.changed == 'true' ||
          github.event_name == 'workflow_dispatch' ||
          github.event_name == 'repository_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/submit_dependency_snapshot.py
