name: dependency-submission

on:
  push:
    branches:
      - main
    paths:
      - "requirements*.txt"
      - "requirements*.in"
      - "requirements*.out"
  workflow_dispatch:

permissions:
  contents: write
  dependency-graph: write

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.11'
      - name: Prepare requirements
        run: |
          python <<'PY'
          from pathlib import Path

          patterns = ("requirements*.txt", "requirements*.in", "requirements*.out")
          excluded = {
              ".git",
              ".hg",
              ".nox",
              ".tox",
              ".venv",
              "__pycache__",
              "env",
              "node_modules",
              "site-packages",
              "venv",
          }

          def is_excluded(target: Path) -> bool:
              return any(part in excluded for part in target.parts)

          for pattern in patterns:
              for path in Path(".").rglob(pattern):
                  if is_excluded(path.parent):
                      continue
                  original = path.read_text()
                  lines = original.splitlines()
                  filtered = []
                  for line in lines:
                      stripped = line.lstrip()
                      if stripped.startswith("ccxtpro"):
                          continue
                      if stripped.startswith("#") and "ccxtpro" in stripped:
                          continue
                      filtered.append(line)
                  if filtered != lines:
                      updated = "\n".join(filtered)
                      if original.endswith("\n"):
                          updated += "\n"
                      path.write_text(updated)
          PY
      - name: Submit dependency snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/submit_dependency_snapshot.py
