name: Dependency Submission

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  security-events: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install build deps
        run: pip install --upgrade pip build
      - name: Validate project
        run: python -m build
      - uses: advanced-security/dependency-submission-action@5530bab9ee4bbe66420ce8280624036c77f89746
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./
