name: dependency-submission

on:
  push:
    branches:
      - main
    paths:
      - "requirements*.txt"
      - "requirements*.in"
      - "requirements*.out"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  security-events: write
  dependency-graph: write

jobs:
  submit:
    permissions:
      contents: write
      id-token: write
      security-events: write
      dependency-graph: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.11'
      - name: Prepare requirements
        run: |
          python <<'PY'
          from pathlib import Path

          patterns = ("requirements*.txt", "requirements*.in", "requirements*.out")
          for pattern in patterns:
              for path in Path(".").glob(pattern):
                  original = path.read_text()
                  lines = original.splitlines()
                  filtered = []
                  for line in lines:
                      stripped = line.lstrip()
                      if stripped.startswith("ccxtpro"):
                          continue
                      if stripped.startswith("#") and "ccxtpro" in stripped:
                          continue
                      filtered.append(line)
                  if filtered != lines:
                      updated = "\n".join(filtered)
                      if original.endswith("\n"):
                          updated += "\n"
                      path.write_text(updated)
          PY
      - name: Submit dependency snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/submit_dependency_snapshot.py
