---
name: Dependency Graph Auto Submission

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  auto-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - name: Component detection
        # yamllint disable-line rule:line-length
        uses: advanced-security/component-detection-dependency-submission-action@v0.1.0
        with:
          detectorArgs: 'Pip=EnableIfDefaultOff'
