name: Build and Push Docker image
permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "main" ]   # или "master", если у тебя так называется основная ветка
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - file: Dockerfile.cpu
            image: myapp-cpu
            artifact: trivy-report-cpu
          - file: Dockerfile.ci
            image: myapp-ci
            artifact: trivy-report-ci
          - file: Dockerfile.gptoss
            image: myapp-gptoss
            artifact: trivy-report-gptoss
    env:
      DOCKERHUB_USERNAME: ${{ secrets.AVERINALEKS }}
      DOCKERHUB_TOKEN: ${{ secrets.BOT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false
          path: bot
      - name: Free disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # main
        timeout-minutes: 10
        continue-on-error: true
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: true
      - name: Prepare build mount dir
        run: |
          sudo mkdir -p /mnt
          if [ -e /dev/buildvg/buildlv ]; then
            sudo wipefs -a /dev/buildvg/buildlv || true
          else
            echo "Device /dev/buildvg/buildlv not found, skipping wipefs"
          fi
            sudo swapoff /mnt/swapfile || true
            sudo rm -f /mnt/swapfile || true
            sudo rm -rf /mnt/* || true
      - name: Install LVM
        run: sudo apt-get update && sudo apt-get install -y lvm2
      - name: Maximize build space
        uses: easimon/maximize-build-space@fc881a613ad2a34aca9c9624518214ebc21dfc0c # v10
        with:
          root-reserve-mb: 4096
          temp-reserve-mb: 100
          swap-size-mb: 4096
          build-mount-path: /mnt
          pv-loop-path: /root-pv.img
          tmp-pv-loop-path: /mnt/tmp-pv.img

      - name: Relocate Docker storage to /mnt
        run: |
          sudo systemctl stop docker
          sudo mv /var/lib/docker /mnt/docker
          sudo ln -s /mnt/docker /var/lib/docker
          sudo systemctl start docker

      - name: Login to Docker Hub
        run: echo "${{ secrets.BOT }}" | docker login --username "${{ secrets.AVERINALEKS }}" --password-stdin

      - name: Prepare buildx cache directory
        run: mkdir -p /mnt/.buildx-cache

      - name: Cache Docker layers
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
        with:
          path: /mnt/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
        with:
          driver: docker-container

      - name: Verify /mnt mount
        run: |
          mount | grep '/mnt'
          df -h /mnt
        working-directory: bot

      - name: Build and push Docker image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25
        with:
          context: .
          file: bot/${{ matrix.file }}
          push: true
          tags: docker.io/${{ env.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest
          cache-from: type=local,src=/mnt/.buildx-cache
          cache-to: type=local,dest=/mnt/.buildx-cache-new,mode=max

      - name: Apply security upgrades in built image
        run: docker run --rm docker.io/${{ env.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest bash -lc "apt-get update && apt-get upgrade -y && apt-get clean && rm -rf /var/lib/apt/lists/*"
        working-directory: bot

      - name: Set up Trivy
        uses: aquasecurity/setup-trivy@9ea583eb67910444b1f64abf338bd2e105a0a93d # v0.2.3
        with:
          version: v0.65.0

      - name: Cleanup before Trivy scan
        run: |
          sudo rm -rf /tmp/* || true
          sudo rm -rf /mnt/trivy-cache /mnt/trivy-tmp || true
          rm -rf ~/.cache/trivy || true
          mkdir -p /mnt/trivy-cache
        working-directory: bot
      - name: Prepare Trivy temp
        run: mkdir -p /mnt/trivy-tmp
        working-directory: bot
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # 0.32.0
        env:
          TMPDIR: /mnt/trivy-tmp
          TRIVY_CACHE_DIR: /mnt/trivy-cache
        with:
          version: v0.65.0
          image-ref: ${{ env.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest
          format: table
          output: bot/${{ matrix.artifact }}.txt
          scanners: vuln

      - name: Show Trivy scan results
        run: cat ${{ matrix.artifact }}.txt
        working-directory: bot

      - name: Upload Trivy report artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ matrix.artifact }}
          path: bot/${{ matrix.artifact }}.txt

      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        if: matrix.artifact == 'trivy-report-ci'
        with:
          name: trivy-report-ci
          path: bot
      - name: Cleanup Docker
        run: |
          docker buildx prune -af || true
          docker system prune -af || true
          rm -rf /mnt/.buildx-cache* || true

  healthcheck:
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false
          path: bot
      - name: Install dependencies
        run: pip install gunicorn flask ccxt python-dotenv requests
      - name: Start data handler service
        id: start_service
        run: |
          scripts/run_data_handler_service.sh --bind 0.0.0.0:8000 &
          echo $! > "$GITHUB_WORKSPACE/service.pid"
          sleep 5
          if ! kill -0 "$(cat "$GITHUB_WORKSPACE/service.pid")" 2>/dev/null; then
            echo "service_running=false" >> "$GITHUB_OUTPUT"
          else
            echo "service_running=true" >> "$GITHUB_OUTPUT"
          fi
        working-directory: bot
      - name: Health check
        if: steps.start_service.outputs.service_running == 'true'
        run: python scripts/health_check.py
        working-directory: bot
      - name: Cleanup
        if: always() && steps.start_service.outputs.service_running == 'true'
        run: |
          kill "$(cat "$GITHUB_WORKSPACE/service.pid")" || true
        working-directory: bot
