name: Build and Push Docker image
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]   # или "master", если у тебя так называется основная ветка
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.AVERINALEKS }}
          password: ${{ secrets.BOT }}
          registry: docker.io

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.cpu
          push: true
          load: true
          tags: averinaleks/myapp:latest

      - name: Set up Trivy
        uses: aquasecurity/setup-trivy@v0.2.3
        with:
          version: v0.65.0

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.32.0
        with:
          version: v0.65.0
          image-ref: averinaleks/myapp:latest
          format: table
          output: trivy-report.txt

      - name: Show Trivy scan results
        run: cat trivy-report.txt

      - name: Upload Trivy report artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt
