name: Build and Push Docker image
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]   # или "master", если у тебя так называется основная ветка

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.AVERINALEKS }}
          password: ${{ secrets.BOT }}
          registry: docker.io

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.cpu
          push: true
          tags: averinaleks/myapp:latest
