name: Build and Push Docker image
permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "main" ]   # или "master", если у тебя так называется основная ветка
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - file: Dockerfile.cpu
            tag: ghcr.io/averinaleks/myapp:latest
            artifact: trivy-report-cpu
          - file: Dockerfile.ci
            tag: ghcr.io/averinaleks/myapp-ci:latest
            artifact: trivy-report-ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.AVERINALEKS }}
          password: ${{ secrets.TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.file }}
          push: true
          load: true
          tags: ${{ matrix.tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Apply security upgrades in built image
        run: |
          docker run --rm ${{ matrix.tag }} bash -lc "apt-get update && apt-get upgrade -y && apt-get clean && rm -rf /var/lib/apt/lists/*"

      - name: Move Docker layer cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Set up Trivy
        uses: aquasecurity/setup-trivy@v0.2.3
        with:
          version: v0.65.0

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.32.0
        with:
          version: v0.65.0
          image-ref: ${{ matrix.tag }}
          format: table
          output: ${{ matrix.artifact }}.txt

      - name: Show Trivy scan results
        run: cat ${{ matrix.artifact }}.txt

      - name: Upload Trivy report artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}.txt

      - uses: actions/download-artifact@v5
        with:
          name: trivy-report-ci
          path: .
