name: Build and Push Docker image
permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "main" ]   # или "master", если у тебя так называется основная ветка
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - file: Dockerfile.cpu
            image: myapp
            artifact: trivy-report-cpu
          - file: Dockerfile.ci
            image: myapp-ci
            artifact: trivy-report-ci
          - file: Dockerfile.gptoss
            image: myapp
            artifact: trivy-report-gptoss

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        timeout-minutes: 10
        continue-on-error: true
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: true
      - name: Clean Docker dir
        run: sudo rm -rf /var/lib/docker/*
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 1024
          temp-reserve-mb: 100
          swap-size-mb: 4096
          build-mount-path: /var/lib/docker
          pv-loop-path: /root-pv.img
          tmp-pv-loop-path: /var/lib/docker/tmp-pv.img

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.AVERINALEKS }}
          password: ${{ secrets.BOT }}

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Verify /var/lib/docker mount
        run: |
          mount | grep '/var/lib/docker'
          df -h /var/lib/docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.file }}
          push: true
          load: true
          tags: ${{ secrets.AVERINALEKS }}/${{ matrix.image }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Apply security upgrades in built image
        run: |
          docker run --rm ${{ secrets.AVERINALEKS }}/${{ matrix.image }}:latest bash -lc "apt-get update && apt-get upgrade -y && apt-get clean && rm -rf /var/lib/apt/lists/*"

      - name: Move Docker layer cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Set up Trivy
        uses: aquasecurity/setup-trivy@v0.2.3
        with:
          version: v0.65.0

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.32.0
        with:
          version: v0.65.0
          image-ref: ${{ secrets.AVERINALEKS }}/${{ matrix.image }}:latest
          format: table
          output: ${{ matrix.artifact }}.txt

      - name: Show Trivy scan results
        run: cat ${{ matrix.artifact }}.txt

      - name: Upload Trivy report artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}.txt

      - uses: actions/download-artifact@v5
        with:
          name: trivy-report-ci
          path: .
