name: Submit package to PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-24.04
    env:
      TOKENPYPI: ${{ secrets.TOKENPYPI }}
    permissions:
      contents: read
    steps:
      - name: Validate token
        run: |
          if [ -z "$TOKENPYPI" ]; then
            echo "TOKENPYPI not set" && exit 1
          fi
      - name: Select branch
        id: select-branch
        run: |
          if git ls-remote --exit-code --heads https://github.com/${{ github.repository }}.git dependabot/pip/openai-1.102.0 >/dev/null; then
            echo "ref=dependabot/pip/openai-1.102.0" >> "$GITHUB_OUTPUT"
          else
            echo "ref=main" >> "$GITHUB_OUTPUT"
          fi
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4 08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          ref: ${{ steps.select-branch.outputs.ref }}
      - name: Free disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # main 54081f138730dfa15788a46383842cd2f914a1be
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
      - name: Clean Docker dir
        run: sudo rm -rf /var/lib/docker/*
      - name: Prepare build volume
        run: |
          if [ -e /dev/buildvg/buildlv ]; then
            sudo wipefs -a /dev/buildvg/buildlv || true
          else
            echo "Device /dev/buildvg/buildlv not found, skipping wipefs"
          fi
          sudo swapoff /mnt/swapfile || true
          sudo rm -f /mnt/swapfile || true
          sudo rm -rf /mnt/* || true
      - name: Maximize build space
        uses: easimon/maximize-build-space@fc881a613ad2a34aca9c9624518214ebc21dfc0c # v10 fc881a613ad2a34aca9c9624518214ebc21dfc0c
        with:
          root-reserve-mb: 1024
          temp-reserve-mb: 100
          swap-size-mb: 4096
          build-mount-path: /mnt
          pv-loop-path: /root-pv.img
          tmp-pv-loop-path: /mnt/tmp-pv.img
      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v5 a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version-file: .python-version
      - name: Create virtual environment
        run: |
          python -m venv /mnt/venv
      - name: Add venv to PATH
        run: echo "/mnt/venv/bin" >> $GITHUB_PATH
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Install pip-tools
        run: |
          source /mnt/venv/bin/activate
          pip install pip-tools==7.5.0
      - name: Generate dependency lock
        run: |
          pip-compile --strip-extras -o requirements.out requirements.txt
      - name: Copy project to /mnt
        run: rsync -a . /mnt/project
      - name: Check dependencies
        working-directory: /mnt/project
        run: |
          pip-compile --dry-run -o requirements.out requirements.txt
      - name: Return generated files
        if: always()
        run: rsync -a /mnt/project/requirements.out requirements.out || true
      - name: Build package
        run: |
          python -m build
      - name: Publish to PyPI
        if: env.TOKENPYPI != ''
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # release/v1 76f52bc884231f62b9a034ebfe128415bbaabdfc
        with:
          user: __token__
          password: ${{ env.TOKENPYPI }}
          attestations: false
          skip-existing: true
      - name: Skip PyPI publish (missing token)
        if: env.TOKENPYPI == ''
        run: echo "TOKENPYPI not set; skipping publish."
      - name: Cleanup buildx
        run: docker buildx prune -af || true
